apiVersion: apps/v1
kind: Deployment
metadata:
  name: aaf-cert-service-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  replicas: {{ .Values.replicaCount }} 
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers:
      - name: aaf-cert-service
        image: {{ .Values.image }}
        ports:
        - containerPort: {{ .Values.containerPort }} 
