apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.server.secret.name }}
type: Opaque
data:
  certServiceServer-keystore.jks:
  {{ (.Files.Glob "resources/certServiceServer-keystore.jks").AsSecrets }}
  certServiceServer-keystore.p12:
  {{ (.Files.Glob "resources/certServiceServer-keystore.p12").AsSecrets }}
  truststore.jks:
  {{ (.Files.Glob "resources/truststore.jks").AsSecrets }}
  root.crt:
  {{ (.Files.Glob "resources/root.crt").AsSecrets }}