apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.client.secret.name }}
type: Opaque
data:
  certServiceClient-keystore.jks:
  {{ (.Files.Glob "resources/certServiceClient-keystore.jks").AsSecrets }}
  truststore.jks:
  {{ (.Files.Glob "resources/truststore.jks").AsSecrets }}
