version: "2.1"

services:
  ejbca:
    image: primekey/ejbca-ce:6.15.2.5
    hostname: cahostname
    container_name: aafcert-ejbca
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./compose-resources/ejbca-configuration.sh:/opt/primekey/scripts/ejbca-configuration.sh
    healthcheck:
      test: ["CMD-SHELL", "curl -kI https://localhost:8443/ejbca/publicweb/healthcheck/ejbcahealth"]
      interval: 10s
      timeout: 3s
      retries: 15
    networks:
      - certservice

  certservice:
    image: onap/org.onap.aaf.certservice.aaf-certservice-api:latest
    container_name: aafcert-service
    volumes:
      - ./certService/helm/aaf-cert-service/resources/cmpServers.json:/etc/onap/aaf/certservice/cmpServers.json
    ports:
      - "8080:8080"
    depends_on:
      ejbca:
        condition: service_healthy
    networks:
      - certservice


networks:
  certservice:
    driver: bridge
