appLabel: aaf-cert-service
replicaCount: 1
repository: onap-dev-local.esisoj70.emea.nsn-net.net
image: kasperki/cert-service:1.0.0
pullPolicy: Always
containerPort: 8080
service:
  type: ClusterIP
liveness:
  initialDelaySeconds: 60
  periodSeconds: 10
readiness:
  initialDelaySeconds: 30
  periodSeconds: 10
healthcheck:
  path: /actuator/health

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 1
    memory: 1Gi